version: "2"

tasks:
  build:
    cmds:
      - go build -o ./build/pg-mig ./cmd/pg-mig/main.go
  test:
    cmds:
      - go test ./...
  coverage:
    cmds:
      - go test -cover ./...
  test_report:
    cmds:
      - go test -coverprofile=coverage/coverage.out ./...
      - go tool cover -html=coverage/coverage.out
