version: "3.7"

services:
  db:
    build:
      context: ./db
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_pass
      - POSTGRES_DB=main_db
    volumes:
      - './db/workspace:/usr/pg-mig/workspace'
