on: push
name: Test and build pg-mig
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: run
        uses: cedrickring/golang-action/go1.15@1.6.0
        env:
          GO111MODULE: "on"