on: push
name: pg-mig master test & build
env:
  GO111MODULE: "on"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.5'

      - name: Run tests
        run: go test -v ./...

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.5'

      - name: Build executable
        run: go build -o ./build/pg-mig ./cmd/pg-mig/main.go

      - name: Upload executable
        uses: actions/upload-artifact@v2.1.4
        with:
          name: pg-mig
          path: ./build/pg-mig
          if-no-files-found: error
